### ISSUE TITLE
Please return to using the same folder and syntax as normal loras

### ISSUE THREAD

**Issue by hollowstrawberry** [KohakuBlueleaf/a1111-sd-webui-lycoris#10]
I have hundreds of safetensors files, we all got used to them working exactly the same as each other, as they should. Now I have to check one by one to see which ones are lycoris and move them to their own folder? That's ridiculous.

**Comment by KohakuBlueleaf** [comment]
Actually you can move all file in to LyCORIS if you want.
LyCORIS extension always support lora

And what's ridiculous is the suggestion you give.
If you have checked how locon ext make what you said possible, you will give up to maintain it.

Or you can just read all the issues in locon ext, and see how many of that is not related to my ext.

If you guys just want old way, just fork it and maintain by yourself. It's in Apache-2 licence.

If you want to say you don't do anything about programming or coding.
Please don't say this decision is "ridiculous"

I don't care about just make all the repo be private.

**Comment by hollowstrawberry** [comment]
Are you trying to say it is hard for a computer to differentiate between lora and lycoris, thus making the old extension unmaintainable?

If so, how can you expect your human users to do the same?

**Comment by hollowstrawberry** [comment]
I now understand you can place all files in the lycoris folder. If so, that's good, and I apologize for being sassy.
