### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by smokeyhallow** [KohakuBlueleaf/a1111-sd-webui-lycoris#12]
Please add some instructions to install for new users! Or atleast some links to do so.

**Comment by AmitShashi** [comment]
@smokeyhallow 
installs from extensions tab then. do this as shown in picture below
![loralycoris](https://user-images.githubusercontent.com/73923245/233782874-e8ebcd46-7c6f-4b43-bc77-4fcc4dcafc1e.JPG)
