### ISSUE TITLE
AttributeError: module 'modules.sd_models' has no attribute 'read_metadata_from_safetensors'

### ISSUE THREAD

**Issue by 4KsTan** [KohakuBlueleaf/a1111-sd-webui-lycoris#14]
![Screenshot (9)](https://user-images.githubusercontent.com/120006006/233321297-8db2be9c-0b72-4c51-b078-17e2824e1a47.png)

**Comment by 4KsTan** [comment]
I cant put safetensors file in LyCORIS File

**Comment by KohakuBlueleaf** [comment]
Your sd-webui version is too old

I will add a notice on the ReadMe

**Comment by 4KsTan** [comment]
ohh ,alright thank you
