### ISSUE TITLE
Error in loading certain Loras in new commit

### ISSUE THREAD

**Issue by jim-22** [KohakuBlueleaf/a1111-sd-webui-lycoris#16]
This part here in the latest commit: https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/f39bc5598b3469aa8a3c757a47b28ee205b0e947#diff-e1a87b3a2658ae7f5d1671f19913fb188fb59a0c6d69029a03baf7ce7d2ec95eR637

Removes the check if whether `module.alpha` is not `None`. This means that sometimes, an error is raised saying `TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'`. This only happens for certain Loras, not sure what that depends on. Can you bring back the None check?

**Comment by KohakuBlueleaf** [comment]
Sorry I just forgot that
Fixed
