### ISSUE TITLE
[Feature]: Add "None" option to LyCORIS dropdown 

### ISSUE THREAD

**Issue by brunogcar** [KohakuBlueleaf/a1111-sd-webui-lycoris#17]
basicly if a lyco is selected on quicksetting, sd_lyco, there is no option to select none back

on A1111 hypernetwork and lora both have same issue, that is fixed with https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9723

vlad applied it do his repo and due to compatibility recommended created a ticket here

https://github.com/vladmandic/automatic/issues/474

**Comment by KohakuBlueleaf** [comment]
@brunogcar I will do that!
Thx for noticing
