### ISSUE TITLE
Critical performance regression due to recent code change

### ISSUE THREAD

**Issue by vladmandic** [KohakuBlueleaf/a1111-sd-webui-lycoris#21]
Not sure if you're monitoring conversation in #20, but the latest code introduced a major performance issue.
If you already are, feel free to ignore/close this.

**Comment by RayHell** [comment]
I confirm, I went from 24 it/s to 3.5it/s. If I remove the plugin I go back to 24 it/s

**Comment by Rkkss** [comment]
Tested it on new git clone with only lycoris installed. Changed from 10it/s to 2.5it/s

**Comment by NaughtDZ** [comment]
New version get slow to 1.00it/s on RTX3070 with 512*512

**Comment by KohakuBlueleaf** [comment]
@vladmandic Already push a fix for this
plz check it

**Comment by wzgrx** [comment]
The latest version is still very slow, and it works normally after removing the extension

**Comment by vladmandic** [comment]
confirm as resolved using latest update with commit hash `3176baed`
