### ISSUE TITLE
How to keep dyn in default value?

### ISSUE THREAD

**Issue by Hotarucon** [KohakuBlueleaf/a1111-sd-webui-lycoris#24]
I trying to use lora block weight (https://github.com/hako-mikan/sd-webui-lora-block-weight) to control lycoris,arguments be like <lyco:"model name":"te value":"unet value":"dyn value":"lora block weight presets">, and I wana KEEP dyn value=default,so what should I input into "dyn value" to keep it use default value?

**Comment by KohakuBlueleaf** [comment]
@Hotarucon I just add a feature that you can use "default" to indicate default value
so maybe something like:
<lyco:name:0.5:default:default:"LBW presets">

(default for unet = use same value as te)

**Comment by Hotarucon** [comment]
Niiiiiiiiiiice,it worked,\thx!/
