### ISSUE TITLE
AttributeError: 'ExtraNetworksPageLyCORIS' object has no attribute 'find_preview'. Did you mean: 'link_preview'?

### ISSUE THREAD

**Issue by devilhookey** [KohakuBlueleaf/a1111-sd-webui-lycoris#29]
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\launch.py", line 361, in <module>
    start()
  File "F:\stable-diffusion-webui\launch.py", line 356, in start
    webui.webui()
  File "F:\stable-diffusion-webui\webui.py", line 205, in webui
    shared.demo = modules.ui.create_ui()
  File "F:\stable-diffusion-webui\modules\ui.py", line 468, in create_ui
    extra_networks_ui = ui_extra_networks.create_ui(extra_networks, extra_networks_button, 'txt2img')
  File "F:\stable-diffusion-webui\modules\ui_extra_networks.py", line 181, in create_ui
    page_elem = gr.HTML(page.create_html(ui.tabname))
  File "F:\stable-diffusion-webui\modules\ui_extra_networks.py", line 94, in create_html
    for item in self.list_items():
  File "F:\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\ui_extra_networks_lyco.py", line 21, in list_items
    "preview": self.find_preview(path),
AttributeError: 'ExtraNetworksPageLyCORIS' object has no attribute 'find_preview'. Did you mean: 'link_preview'?

**Comment by devilhookey** [comment]
use link_preview next line put error

  File "F:\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\ui_extra_networks_lyco.py", line 22, in list_items
    "description": self.find_description(path),
AttributeError: 'ExtraNetworksPageLyCORIS' object has no attribute 'find_description'

**Comment by DingDong-BingBong** [comment]
Getting the exact same error. I just made an account to post about it here, but seems like you were a few steps ahead of me.

Hope this can get fixed soon!

**Comment by alemanimani** [comment]
To fix, go to your webui-user.bat that you use to launch 1111, 

before the last list add "git pull" 

and it will auto update your stable diffusion auto111 etc, every time you  open. 

if you don't want to auto update then.. probably don't but this solved my error with lyco

**Comment by coding2themoon** [comment]
Same error. Fixed it by creating venv with python 3.10.6 and updating sd webui. I failed many times in updating sd webui, which is probably because my previous venv was created with python 3.9.x in conda. Later I installed python 3.10.6 and reset the path for python in webui-user.bat. A third-party launcher helped me a lot. If you can read Chinese, check this link to download. https://www.bilibili.com/video/BV1ne4y1V7QU/?spm_id_from=333.337.search-card.all.click&vd_source=30012a7665c1c20eb18e4b853ba35401

**Comment by devilhookey** [comment]
it fix ,thx to all

**Comment by Tom945233** [comment]
> 
@ devilhookey
Can you tell me how to fix  it ？ I tried many ways but it didn't work.

**Comment by Tom945233** [comment]
@ devilhookey
Can you tell me how to fix it ？ I tried many ways but it didn't work.

**Comment by jamball68** [comment]
Yes, please. I too have updated to the latest Automatic 1111 and am still receiving this message. Thank you.

**Comment by nobodynuf** [comment]
I had the same error even after using the latest commit of stable diffusion webui (baf6946e06249c5af9851c60171692c44ef633e0).

I resolved it for now adding a dummy function in 
stable-diffussion-webui\extensions\a1111-sd-webui-lycoris\ui_extra_networks_lyco.py

![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/22306937/ccc85bfa-e6d8-4837-8aa5-29e86aeae0d9)

This is only to fix the crash when enumerating extra networks. And this makes the preview of Lycoris not available

I hope this helps ;-;
