### ISSUE TITLE
lycoris to load the model has no effect

### ISSUE THREAD

**Issue by iconnoci** [KohakuBlueleaf/a1111-sd-webui-lycoris#3]
I use lycoris to load the model, but it has no effect. Loading with lora will have an effect. Am I using it wrong? attach model information

 "ss_sd_model_name": "v1-5-pruned-emaonly.ckpt",
    "ss_resolution": "(512, 512)",
    "ss_clip_skip": "2",
    "ss_num_train_images": "140",
    "ss_tag_frequency": {
        "20_jianzhuwu": {
            "jianzhuwuartstyle a small blue house with a blue roof and a sign that says \" the word \" on it.": 1,
            "jianzhuwuartstyle a cartoon drawing of a house with a deer head on top of it.": 1,
            "jianzhuwuartstyle a drawing of a house with a fish on it": 1,
            "jianzhuwuartstyle a drawing of a purple house with a purple roof.": 1,
            "jianzhuwuartstyle a small house with a green roof and a sign that says \" the store is on the top. \"": 1,
            "jianzhuwuartstyle a small house with a gun on the roof": 1,
            "jianzhuwuartstyle a drawing of a house with a green roof and a sign that says \" pirate \".": 1
        }
    },
    "ss_batch_size_per_device": "1",
    "ss_bucket_info": "null",
    "ss_bucket_no_upscale": "False",
    "ss_cache_latents": "True",
    "ss_caption_dropout_every_n_epochs": "0",
    "ss_caption_dropout_rate": "0.0",
    "ss_caption_tag_dropout_rate": "0.0",
    "ss_color_aug": "False",
    "ss_dataset_dirs": {
        "20_jianzhuwu": {
            "n_repeats": 20,
            "img_count": 7
        }
    },
    "ss_enable_bucket": "False",
    "ss_epoch": "10",
    "ss_face_crop_aug_range": "None",
    "ss_flip_aug": "False",
    "ss_full_fp16": "False",
    "ss_gradient_accumulation_steps": "1",
    "ss_gradient_checkpointing": "True",
    "ss_keep_tokens": "0",
    "ss_learning_rate": "0.0001",
    "ss_lowram": "False",
    "ss_lr_scheduler": "constant",
    "ss_lr_warmup_steps": "0",
    "ss_max_bucket_reso": "None",
    "ss_max_grad_norm": "1.0",
    "ss_max_token_length": "None",
    "ss_max_train_steps": "1400",
    "ss_min_bucket_reso": "None",
    "ss_mixed_precision": "fp16",
    "ss_network_alpha": "8.0",
    "ss_network_args": {
        "conv_dim": "4",
        "conv_alpha": "1",
        "algo": "lora"
    },
    "ss_network_dim": "8",
    "ss_network_module": "lycoris.kohya",
    "ss_new_sd_model_hash": "cc6cb27103417325ff94f52b7a5d2dde45a7515b25c255d8e396c90014281516",
    "ss_noise_offset": "0.1",
    "ss_num_batches_per_epoch": "140",
    "ss_num_epochs": "10",
    "ss_num_reg_images": "0",
    "ss_optimizer": "bitsandbytes.optim.adamw.AdamW8bit",
    "ss_output_name": "jianzhuwuArtStyle",
    "ss_prior_loss_weight": "1.0",
    "ss_random_crop": "False",
    "ss_reg_dataset_dirs": {},
    "ss_sd_model_hash": "81761151",
    "ss_sd_scripts_commit_hash": "9c8c480f8e654eeb5a7d92c13b4ce04333840b0c",
    "ss_seed": "1234",
    "ss_session_id": "147056358",
    "ss_shuffle_caption": "False",
    "ss_text_encoder_lr": "5e-05",
    "ss_total_batch_size": "1",
    "ss_training_comment": "None",
    "ss_training_finished_at": "1681105281.02053",
    "ss_training_started_at": "1681103916.6504002",
    "ss_unet_lr": "0.0001",
    "ss_v2": "False",
    "sshs_legacy_hash": "7c3adc16",
    "sshs_model_hash": "4e5c0407382898ee91a2f8f839a4d2b1f9f94f119744fa7018816dfd228fb4ef"

**Comment by KohakuBlueleaf** [comment]
what's your sd-webui commit?

**Comment by Kepler-16b** [comment]
@KohakuBlueleaf Hey, I've upgrade to [a9fed7c3](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a9fed7c364061ae6efb37f797b6b522cb3cf7aa2), which is ahead of the ce68ab8 commit that you mentioned. The extension works, the LyCORIS tab is showing up as intended, but I also encounter this issue. All of the LoHA model now have no effects.

**Comment by KohakuBlueleaf** [comment]
@Kepler-16b I will check a9fed7c3
I only test this extension on the latest (the 22.... one)

**Comment by KohakuBlueleaf** [comment]
@Kepler-16b I have asked other ppl who using a9fed7c3
And they report that all the things are working normal
I'm sorry that if I don't get the loha file you are using, I cannot check which thing cause this bug

And you can also check if your extension is latest

**Comment by iconnoci** [comment]
@KohakuBlueleaf  The model has been uploaded, please test it.

**Comment by KohakuBlueleaf** [comment]
@iconnoci @Kepler-16b I have pushed a fix for some bugs that my related to you guys' problem
please check it

**Comment by iconnoci** [comment]
@KohakuBlueleaf  Sorry, I updated the webui to 22bcc7b, now it is normal, see @Kepler-16b's

**Comment by iconnoci** [comment]
@KohakuBlueleaf 
I switched to a9fed7c364061ae6efb37f797b6b522cb3cf7aa2 again, but the latest version of webui cannot be used, and the results cannot be displayed. . . . , or switch back to the old version.

I pulled the 91b6366292ca49c5d5f364d0e13f2ba3ec28397f of the a1111-sd-webui-locon
I pulled the b20ccd742a754fa49f81dd7ef7188a46d2613329 of the a1111-sd-webui-lycoris
The latest update doesn't seem to work either.

**Comment by iconnoci** [comment]
@KohakuBlueleaf 
I switched to a9fed7c364061ae6efb37f797b6b522cb3cf7aa2 again, but the latest version of webui cannot be used, and the results cannot be displayed. . . . , or switch back to the old version.

I pulled the b20ccd742a754fa49f81dd7ef7188a46d2613329 of the lycoris extension
The latest update doesn't seem to work either.


test:  1girl,cartoonchar1artstyle , cartoon ,<lyco:cartoonChar1ArtStyle-000007:1000>
The weight is 1000. It is said that the picture should have exploded long ago, but it has no effect. . . . .

**Comment by KohakuBlueleaf** [comment]
are you sure your model is in LyCORIS folder?

**Comment by iconnoci** [comment]
Am I right?
![QQ截图20230412103205](https://user-images.githubusercontent.com/22522962/231332827-c63463e8-a8ee-4e91-a85d-2d9ceac36bc3.png)
![QQ截图20230412103229](https://user-images.githubusercontent.com/22522962/231332836-38fd5f6b-de7e-4c74-a134-7532ad297194.png)
![QQ截图20230412103314](https://user-images.githubusercontent.com/22522962/231332921-6b3cae37-4737-4ec2-848a-425bb48ef118.png)

**Comment by iconnoci** [comment]
我把所有扩展插件都给禁用了就剩下你的插件，结果效果正常了，进下来我会在一个一个的启动看看是哪个扩展搞事情啊。。。。。

**Comment by iconnoci** [comment]
不知道你的扩展里是否又它stable-diffusion-webui-composable-lora   只要这个扩展被安装了 ，貌似就记住了上次的lyco使用的结果（有使用过lyco就会有效，如果没有 在写lyco也是没效果的。。。），你可以测试一下

**Comment by KohakuBlueleaf** [comment]
composable lora跟新的sd-webui lora系統(包括我這套lyco)的寫法是完全衝突的
而且composable lora也已經一個半月沒更新了
別想了(

**Comment by iconnoci** [comment]
所以我去掉了composable lora，[multidiffusion-upscaler-for-automatic1111](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111) 这个不用它好像也可以分区使用lora

**Comment by CB5K** [comment]
The Lycoris seems to be working in general and creates the character in the style of the LoRA but I don't have a Lycoris tab even with the extension installed

**Comment by Kepler-16b** [comment]
更新到最新commit确实解决了。好像也没别的选择，seg anything相关的插件也都只能在新版使用。感谢。

**Comment by iconnoci** [comment]
@Kepler-16b 你最新版webui 出图的时候不会显示上一次图，本次生成的不显示吗？
