### ISSUE TITLE
Enhancement: Modification of  a1111-sd-webui-lycoris to act as standard lora/lycoris handler

### ISSUE THREAD

**Issue by TheOnlyHolyMoly** [KohakuBlueleaf/a1111-sd-webui-lycoris#34]
Preface: Built-in lora extension is currently incapable of handling many new lora formats. Lycoris extension is capable of handling such formats very well. 

Goal:  Enabling a1111-sd-webui-lycoris extension to act as default lora and lycoris handler for webui
Specs: See below
(edited as per Vlad's comment below).

**Comment by vladmandic** [comment]
as per conversation in <https://github.com/kohya-ss/sd-scripts/issues/397>, i'm ok with @KohakuBlueleaf creating an additional cmd_opts flag (for example `--lyco-patch-lora`). i can control that programatically as needed and that way there would be no need for per-repo specific work here.

**Comment by vladmandic** [comment]
this feature would be optional to start with, so it doesn't have to have optional feature parity, only functional feature parity.
but yes, it would be a nice-to-have. definitely not mandatory for an optional feature.

**Comment by TheOnlyHolyMoly** [comment]
so basically, it is up to @KohakuBlueleaf to provide the enhanced version with the cmd_opts flag.

**Comment by KohakuBlueleaf** [comment]
@vladmandic I have tried something on this feature
and it looks like if you want to get <lora> and <lyco> both working on same backends will be a little bit tricky
I will make --lyco-patch-lora works like: make lycoris ext to read lora_dir and make lycoris ext to use <lora> 
but lyco dir and <lyco> will be disabled
is this ok?

**Comment by vladmandic** [comment]
yes, thats fine with me. in general, if one handler can handle everything there is no need for separate folders.

**Comment by KohakuBlueleaf** [comment]
@vladmandic I have pushed a commit for this feature
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/59680068/26e5109d-f120-43fc-ad3c-f2207c8bd8f0)
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/59680068/c8c00808-f76e-4b85-a008-2c76dbdae5ba)

**Comment by Dasor92** [comment]
Just tried it, it's not working at all, the lora is "loaded" and no errors are thrown but the image is the exact same, and the lora doesn't modify anything

**Comment by vladmandic** [comment]
first, its loading from `lyco_dir`, not `lora_dir` - i'm ok with that, just worth noting.

second, selecting lora from extra networks does some weird tag-to-filename matching, never looked into that, will dive in. anyhow, specifying exact filename in prompt manually works, selecting lora from extra networks is buggy

third - and this is a big one - results are veeeery different.
i've tried some locons/lycos which do miss details when using lora interpreter (which is obvious since it doesn't know what to do with extra layers), but big issue is with some simple loras.

here's an example - above is using lyco and below is using lora interpreter:
![test](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/57876960/b225a1cc-2f57-4353-9cf5-a18ba33c2bfc)

as it is, the differences are just too big to be a possible replacement to built-in lora

**Comment by KohakuBlueleaf** [comment]
@vladmandic ?
It is loading from lora dir

**Comment by KohakuBlueleaf** [comment]
Ih ok I know why
I remove the extra ui
But I cannot remove extra ui from built in lora so it will be a problem if I add it back

**Comment by KohakuBlueleaf** [comment]
(there will be 2 Extra network ui for same dir, and both will generate<lora> format)

**Comment by vladmandic** [comment]
where its loading from and what extra network pages are shown is more cosmetic - worth fixing if results are similar to original. otherwise ppl will complain too much (and right now results are very different).

**Comment by KohakuBlueleaf** [comment]
@vladmandic 
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/59680068/3d210035-0465-4767-ab24-2e1964d782fd)

I pushed another version, which also patch the extra network ui
and I just make "exact same" image with it

without changing any compute part.

BTW If you are comparing between lycoris and old lora implementation, this kind of differences is quite normal

**Comment by KohakuBlueleaf** [comment]
Here is the exact same prompt(but use lyco+lora, instead all by lyco) same seed and same model:
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/59680068/475ee05d-7c55-46b7-ba58-f138da8d2063)

I think they are identical

**Comment by KohakuBlueleaf** [comment]
oh wait
which locon/lora are you using for comparing?

**Comment by vladmandic** [comment]
for example, <https://civitai.com/models/7102/blatap3>

**Comment by KohakuBlueleaf** [comment]
@vladmandic I think I found the reason.
A1111 use F.conv2d to rebuild the conv2d weight from 2matrix....
I can use exact same operator but it just
ugly

**Comment by KohakuBlueleaf** [comment]
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/59680068/18003e40-a258-472c-abb7-a1af80fb0d7e)
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/59680068/67c238fd-2bfc-4198-a2e9-39c392eb3790)

There are the differences

**Comment by KohakuBlueleaf** [comment]
(I already checked they will not give same result, due to numerical error)

**Comment by vladmandic** [comment]
I have few ideas how to handle that, but need to run now, let's catch up tomorrow.

**Comment by KohakuBlueleaf** [comment]
@vladmandic You can check the lora dir part
and the extra network ui

**Comment by KohakuBlueleaf** [comment]
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/59680068/11aca64d-0947-4aa8-a14f-512fcd4cecd4)

**Comment by TheOnlyHolyMoly** [comment]
I think it could be worth thinking about having two methods available (like the legacy type with the "ugly" conv2d and the improved type with the better conv2d)....and then calling legacy from prompt by lora: and new form by nlora: for example? That way we'd keep the reproducability of images whilst still enabling better tech. I would appreciate the creative options from such switching..

**Comment by KohakuBlueleaf** [comment]
@vladmandic @TheOnlyHolyMoly 
I do some more test on it......

I just find that I cannot reproduce "different output"
I have gotten different output but it is caused by the order, not bcuz different implementation

@vladmandic Here is my test result
both lora means both using lycoris
lora + lyco means built-in lora + lycoris

![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/59680068/98c13a24-ebc4-4052-9c59-6f57f9939043)
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/59680068/948f422f-18d5-4dd0-8c84-a92a5fc70e5d)

**Comment by KohakuBlueleaf** [comment]
different implementation didn't affect the result here actually

**Comment by KohakuBlueleaf** [comment]
@vladmandic I also tried the model you post
which also produce exact same image from built-in lora and lycoris
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/59680068/757f1b7d-c99d-45d5-86d9-a98b6d839544)

![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/59680068/6bc6a580-d529-4054-9de7-e2350e18585b)

**Comment by TheOnlyHolyMoly** [comment]
Interesting... reminds me of the discrepancy that I had in my other enviroments... maybe it's something in the settings that makes the difference here between same/different?

**Comment by TheOnlyHolyMoly** [comment]
When I want to test this too, do I need to git-pull this manually from within lycoris extension folder? since the extension tab does not show me available updates

**Comment by KohakuBlueleaf** [comment]
> When I want to test this too, do I need to git-pull this manually from within lycoris extension folder? since the extension tab does not show me available updates

You can try that
if you have same git commit in extension tab and in this repo's main branch
I think you can just try it?

**Comment by TheOnlyHolyMoly** [comment]
okay, so i ran a test lora: vs. lyco: with and without patch enabled.

![Lyco Patch - Delta Comparison 1](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/131612312/6be9b6ca-5b65-42a0-9aec-817bd56374ab)

So, according to my test results - doubled checked as I could not believe it in the end - lora and lyco deliver the same result with this lora file. However, when the lyco-patch is enabled in settings they both give a different result (again the same). The deviation is there but small, I made an overlay luminance-matching, so the grey areas are where the two images deviate. 
I have no practical explanation why Lycoris Extension would behave differently with switch on or off... @vladmandic @KohakuBlueleaf 

![Lyco Patch - Delta Comparison](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/131612312/18c5c158-1a57-48b4-8997-2bf11a8c0f81)


**For Reproduction**
Prompt: RAW, best quality, masterpiece, novelAI, trending on 500px full body photo of a Australian <lora:BlaTap3:1> 25yo girl, pole dancing, smile, hyperdetailed, shiny skin, detailed skin, detailed face, sharp focus,8k canon RAW
Negative prompt: text, logo, artwork, drawing, painting, cg, anime, rendering, manga, High pass filter, airbrush, portrait, zoomed, soft light, smooth skin, closeup, fake, cartoon, deformed, extra limbs, extra fingers, mutated hands, bad anatomy, bad proportions, blind, bad eyes, ugly eyes, dead eyes, blur, vignette, out of shot, out of focus, gaussian, closeup, monochrome, grainy, noisy, ((text)), ((writing)), ((logo)), oversaturation, over saturation, overshadow, censorship, ugly, deformed, amateur drawing, odd, cell shading, lowres, bad anatomy, bad hands, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, ((signature)), ((watermark)), username, blurry, out of focus, bad hands, poorly drawn hands, holding, hands, fingers, (((multiple views))), long body, (bad_prompt:0.8)
Steps: 40 | Sampler: DPM++ SDE | CFG scale: 10 | Seed: 3401190540 | Face restoration: CodeFormer | Size: 512x832 | Model hash: 40f9701da0 | Model: uberRealisticPornMerge_urpmv13 | VAE: vae-ft-mse-840000-ema-pruned (1) | Clip skip: 1 | Version: 9726b4d | Parser: Full parser | Lora hashes: BlaTap3: 73bf532fd332 | Dynamic thresholding enabled: True | Mimic scale: 7 | Threshold percentile: 100

SD Lycoris Extension Commit 21e9ea0f // Sun Jun04 2023 13:49

Using VENV: E:\VLADautomatic\venv
22:53:15-139802 INFO     Running extension preloading
22:53:15-353797 INFO     Starting SD.Next
22:53:15-356798 INFO     Python 3.10.6 on Windows
22:53:15-614830 INFO     Version: 9726b4d2 Sun Jun 4 13:21:52 2023 -0400
22:53:16-384820 INFO     Setting environment tuning
22:53:16-390799 INFO     nVidia CUDA toolkit detected
22:53:29-326883 INFO     Torch 2.0.0+cu118
22:53:29-416859 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
22:53:29-421852 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24563 Arch (8, 9) Cores 128
22:53:29-424852 INFO     Verifying requirements
22:53:29-463852 INFO     Installing packages
22:53:29-677851 INFO     No changes detected: Quick launch active
22:53:29-679856 INFO     Running extension preloading
22:53:29-681852 INFO     Server arguments: []

**Comment by KohakuBlueleaf** [comment]
BTW
What's your extension list like?

**Comment by TheOnlyHolyMoly** [comment]
Extension	Current version
LDSR	
ScuNET	
a1111-sd-webui-lycoris	c1e676b4
clip-interrogator-ext	9e6bbd9b
multidiffusion-upscaler-for-automatic1111	70b3c5ea
prompt-bracket-checker	
sd-dynamic-thresholding	f02cacfc
sd-extension-aesthetic-scorer	b60c3c82
sd-extension-steps-animation	13e5b455
sd-extension-system-info	        064c856a
sd-webui-controlnet	                e78d486c
sd-webui-model-converter	        f6e0fa53
seed_travel	                                4bc8b2f1
stable-diffusion-webui-images-browser	59547c84
stable-diffusion-webui-rembg	657ae9f5

**Comment by KohakuBlueleaf** [comment]
this may caused by some dtype things
I'm checking

**Comment by vladmandic** [comment]
ok, i though how to simplify testing of this so i actually implemented a totally different feature - extra networks can now be selected in xyz grid :)

and i tested using ~20 loras (now its easy).
- results when using `lora` and `lyco` are nearly identical (within margin of error of undeterministic cross-optimization)
- results when using `lyco-as-lora` are pretty much always slightly different - big picture is the same, but details actually change.

examples:
- [lora](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/57876960/90d6bc40-128a-4b31-8759-171997385307)
- [lyco](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/57876960/aa25b802-dbb6-4d12-8ddd-db0b0ef27888)
- [lyco-as-lora](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/57876960/89a0e84a-c57a-457f-935d-b03f94748da2)

ignore differences in `magmui`, that is expected as that is locon model so it doesn't get correctly interpreted in lora
but look for example at `dreamshaper` - picture frame in the background moved

and those subtle differences are in every single example

**Comment by KohakuBlueleaf** [comment]
I'm pretty sure lot of ppl just ignore all the one line warning (

I can remove it if you want.

**Comment by KohakuBlueleaf** [comment]
@vladmandic I have found a tiny bug for sd2.x lyco models
but still cannot reproduce and find any thing that can cause this kind of different on SD1.x models in my code.

**Comment by TheOnlyHolyMoly** [comment]
If it were only lora interpretation changing upon patch-activation it would surprise me far less than also LYCO: changing its behavior of lora interpretation upon patch activation...could be be something about the lora-extension getting disabled?

**Comment by KohakuBlueleaf** [comment]
BTW, will you guys disable built-in lora in extension tab when test this?

**Comment by vladmandic** [comment]
you mean did we disable it for this test or will we disable it completely in the future? 
for this test, i left it as-is - i plan one more test tomorrow with built-in lora removed.
for future, my goal is to disable built-in lora and rely on lyco as default.

**Comment by KohakuBlueleaf** [comment]
@vladmandic yeah
I found that built-in lora has something left even if I remove it from extranetwork dictionary
For me this didn't affect anything but I don't know if this actually affect something or not

**Comment by vladmandic** [comment]
i've just spent 2h looking at this and i'm even more confured.
and i've turned on deterministic mode so there is no variation due to other factors.
here's a grid
- lora-default  
  using built-in lora as-is
- lyco-default
  using lyco extension and it produces 100% identical results to lora
- lyco-patch-default
  using lyco-patch-lora and leaving built-in lora as-is. results are quite different.
- lyco-patch-with-lora-disabled
  using lyco-patch-lora and disabling built-in lora. results are closer to original, but still not exactly the same
- lyco-patch-with-lora-disabled
  using lyco-patch-lora and completely removing extensions-builtin/Lora. getting even closer to original but **still** not exactly the same
- lyco-with-lora-disabled
  just using lyco and disabling built-in lora. veeery close, but still few pixels off

differences are best seen in the vertical signs (larger blue sign and smaller b&w sign) to the left of the subject
what is somewhat expected is that
- lora and lyco-patch-lora while built-in lora is still enabled are different since lora still does its hijacks even if its not actively used

what's confusing is:
- how is using `lyco-patch-lora` and just `lyco` any different if built-in lora is disabled? it shouldn't be
  logically, any difference between those two must be up to lyco extension and implementaion of lyco-patch-lora  
- how is disabling built-in lora and fully removing it any different? i though it could be a stray import somewhere, but i've added print statements to ever lora file and they are for real never imported. so if they are never imported, how does their existance change anything??? yes, difference is not huge, but its there

![grid](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/57876960/a3d10600-3d37-4b74-9d31-cd0d6beedbe9)

**Comment by TheOnlyHolyMoly** [comment]
maybe lyco extension is getting hijacked as whole by SD when setting itself as primary lora controller ... that could explain why lyco is acting differently upon patching. I think there is value in registering the lora-lyco-patch with lora2:
then we'd have lora: controlled by lora-legacy and lyco: and lora2: by lyco extension, I guess that way we could rule out that the patch mode as such has a flaw...?

**Comment by KohakuBlueleaf** [comment]
> maybe lyco extension is getting hijacked as whole by SD when setting itself as primary lora controller ... that could explain why "lyco:" is acting differently upon patching. I think there is testing-value in registering the lora-lyco-patch with lora2: then we'd have "lora:" controlled by lora-legacy and "lyco:" and "lora2:" by lyco extension, I guess that way we could rule out that the patch mode as such has a flaw...?

I don't know what are you talking
Since all the "ExtraNetwork" class are stand alone with the SD model
And only SD be hijacked by ExtraNetwork

**Comment by KohakuBlueleaf** [comment]
> maybe lyco extension is getting hijacked as whole by SD when setting itself as primary lora controller ... that could explain why "lyco:" is acting differently upon patching. I think there is testing-value in registering the lora-lyco-patch with lora2: then we'd have "lora:" controlled by lora-legacy and "lyco:" and "lora2:" by lyco extension, I guess that way we could rule out that the patch mode as such has a flaw...?

And What you talking is totally meaningless
Since the goal of this enhancement is: use <lora> to use lyco

No matter you use lora2 or what, if you are not using <lora> it is meaningless

**Comment by KohakuBlueleaf** [comment]
Basically, I'm trying to move lora to lora-legacy (or old lora)
When before_ui in lycoris is triggered

And look if this can solve the problem

**Comment by KohakuBlueleaf** [comment]
@vladmandic I think the problem here is
When I use my locon model to test
it give me totally identical result with: patched lora/lora/lyco
So basically I have no way to check if my code can resolve anything
since in my environment
there is not thing undeterministic
(I'm even using xformers, but there is not thing different between all images, not even 1pixel)

**Comment by KohakuBlueleaf** [comment]
normal lora / normal lyco:
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/59680068/a6b38e56-fe6f-4ed5-8296-ac74f4b58cdd)

lyco patched lora (remove lora from extram_network_registry, didn't disable/remove it)
![12729-2023-06-07_e551839165_kohaku-v3-rev2_968696225_ab417352-512x512](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/59680068/ebedc85e-99a0-443f-b7cd-c44337b8dc9e)

move lora to lora_legacy, register lyco as lora:
![xyz_grid-0650-2023-06-07_e551839165_kohaku-v3-rev2_968696225_d5095cf2-1024x591](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/59680068/9aac338a-082d-4a0b-98e7-cfb544a34b39)

I just get totally identical result with all 5 different setups

I will push the final one to lyco-patch-lora branch, so you guys can test it.

**Comment by vladmandic** [comment]
@KohakuBlueleaf let me know when you've pushed the new code & i'll test it.
btw, i think your test image may be overly simple - i don't see any differences in the foreground subject, all of the differences are in the busy background only

i've penciled them here:
![highlight](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/57876960/9bde9736-6434-43c4-89a6-43f6d7ce2fee)

**Comment by KohakuBlueleaf** [comment]
@vladmandic I think the problem is
Even if my sample is too simple
It should have some pixel different

But there is not
Not only my eyes can distinguish them, numpy also said they have exact same pixel value.

And my new code is in lyco-patch-lora branch
You can try it

**Comment by vashter** [comment]
Hello ok I got a few things I want to say.
1. I'm on 1.3.2. SD Web1111
2. Lycoris is showing up "skipping unknown extra" and when I went to delete the extension, add new one
3. the cmd isn't showing up if it loading weight at all
4. what should I do?
5. I'm using sd-webui-lycoris + kohya_ss extension
6.  I've try lyco-patch-lora and it still give me a unknown skip 
Here is the image... 
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/135835758/ad3853f7-da72-4ece-b65d-296f26ab3c1a)

any help would be great and thanks

**Comment by KohakuBlueleaf** [comment]
> Hello ok I got a few things I want to say.
> 
> 1. I'm on 1.3.2. SD Web1111
> 2. Lycoris is showing up "skipping unknown extra" and when I went to delete the extension, add new one
> 3. the cmd isn't showing up if it loading weight at all
> 4. what should I do?
> 5. I'm using sd-webui-lycoris + kohya_ss extension
> 6. I've try lyco-patch-lora and it still give me a unknown skip
>    Here is the image...
>    ![image](https://user-images.githubusercontent.com/135835758/244053065-ad3853f7-da72-4ece-b65d-296f26ab3c1a.png)
> 
> any help would be great and thanks

Skipping unknown extra network means sd-webui doesn't get any extranetworks for <lyco>

It is very likely your extension didn't load correctly

And BTW, it is normal that <lyco> will become unusable once you turn on the --lyco-patch-lora
Since it will disable <lyco>

**Comment by vladmandic** [comment]
@KohakuBlueleaf i've just repeated bunch of tests and i might have been chasing wrong thing:

there are subtle differences when using lyco-patch-lora and built-in-lora is still enabled
i do somewhat expect since lora does some init code on extension load that cannot be skipped.
so lyco-patch-lora should be used together with disable built-in-lora for best effect.
yes, it works without it disabling lora and its not a big deal, but imo, this is best practice and i can handle that from my side.

any remaining differences seem to be due to non-determinism between my server restarts. even if i use no cross-attention and simplest euler a sampler, there are still some minute numerical differences for identical prompts - this is not due to lora or lyco.

and non-deterministic differences are limited to areas where denoiser has to approximate results more since sampler did not finish (increasing number of steps removes differences) and it depends on precision of vae used - that's why they appear in background details only to start with and are more visible with some models than others. this is an interesting math problem to chase down (eventually), but nothing related to lora/lyco.

as it is, i'm happy with the code as-is - and thank you for all the support.

**Comment by KohakuBlueleaf** [comment]
@vladmandic so basically
Just use the code in main branch?
With disabled lora?

**Comment by vashter** [comment]
> > Hello ok I got a few things I want to say.
> 
> > 
> 
> > 1. I'm on 1.3.2. SD Web1111
> 
> > 2. Lycoris is showing up "skipping unknown extra" and when I went to delete the extension, add new one
> 
> > 3. the cmd isn't showing up if it loading weight at all
> 
> > 4. what should I do?
> 
> > 5. I'm using sd-webui-lycoris + kohya_ss extension
> 
> > 6. I've try lyco-patch-lora and it still give me a unknown skip
> 
> >    Here is the image...
> 
> >    ![image](https://user-images.githubusercontent.com/135835758/244053065-ad3853f7-da72-4ece-b65d-296f26ab3c1a.png)
> 
> > 
> 
> > any help would be great and thanks
> 
> 
> 
> Skipping unknown extra network means sd-webui doesn't get any extranetworks for <lyco>
> 
> 
> 
> It is very likely your extension didn't load correctly
> 
> 
> 
> And BTW, it is normal that <lyco> will become unusable once you turn on the --lyco-patch-lora
> 
> Since it will disable <lyco>

How do I get it load correctly then?

**Comment by vashter** [comment]
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/135835758/0f22a680-3304-4b88-a5bd-e24b2225bcb4)
@KohakuBlueleaf even it is in the extra network, it just doesn't show if it loading weight to allow me to know it working.

**Comment by vashter** [comment]
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/135835758/9fbe5263-db21-4677-a401-577f2d6d99c8)
 so I try with lora while having lycoris model and I get this "locon load lora method"

**Comment by vashter** [comment]
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/135835758/97808236-4db8-4921-ad14-cc06079a3a0f)
I try to reinstall Lycrois and I get this error something about script issue.

**Comment by vashter** [comment]
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/135835758/b001d2ea-3632-4a6e-8269-400d228c7d81)
I try a different lyconis and nothing show up in cmd, try in a lora that cmd showing that but not the loading weight like the screenshot above.. is something conflict the coding or so?

**Comment by KohakuBlueleaf** [comment]
@vashter webui has something wrong I guess
Checking

And you should uninstall locon ext
It is deprecated

**Comment by vashter** [comment]
@KohakuBlueleaf I went on did a fresh install of SD, haven't gotten the lycrois to work yet in cmd showing up weight some reason even with your latest update + SD 1.3.2 as well and no rush let me know what up

**Comment by Dasor92** [comment]
why forcing users who use --lyco patch lora to have their loras inside of Lycoris tab? It breaks almost every extensions (like for example civitai helper)

**Comment by 2blackbar** [comment]
So in the end all the loha lycoris lowhatever models arent that much better than regular loras ? Ive yet to see side by side comparisong with same training data and noticeably better results and not just for clothes of anime char but for likeness of human face.

**Comment by KohakuBlueleaf** [comment]
> So in the end all the loha lycoris lowhatever models arent that much better than regular loras ? Ive yet to see side by side comparisong with same training data and noticeably better results and not just for clothes of anime char but for likeness of human face.

What you said is meaningless in this feature
The thing is, all the model can load/run by built-lora, can also run by my extension.
But lycoris model cannot.

So @vladmandic want to remove built-in lora in his repo.
Which need my extension to replace the built-in lora to ensure ppl can use the old generation parameters

**Comment by vladmandic** [comment]
i agree. @2blackbar you have fundamental misunderstaanding what is the point here - lyco is not different, its superset. if you use lora, it just works with lyco. if you train locon or lyco or anything thats not standard lora, it doesn't work with built-in lora support.

**Comment by TheOnlyHolyMoly** [comment]
@vladmandic since the feature is implemented and generally works, I would go ahead and close this thread, will that be okay for?

**Comment by vladmandic** [comment]
Yes, that's OK with me

**Comment by TheOnlyHolyMoly** [comment]
Thank you @KohakuBlueleaf for making it happen!!
