### ISSUE TITLE
Caching mistakes in "Hires. fix" by LyCORIS? LyCORIS model settings called in the past with <lyco:> are resurrected again when Hires. fix.

### ISSUE THREAD

**Issue by leoftm** [KohakuBlueleaf/a1111-sd-webui-lycoris#38]
LyCORIS model settings called in the past with <lyco:> are resurrected again when Hires. fix.

Example:
1st prompt & Hires. fix
<lyco:lora-weights:0.2:1.5>→
```
========================================
Apply LyCORIS model: lora-weights
Text encoder weight: 0.2
Unet weight: 1.5
DyLoRA Dim: None
========================================
(Here is the progress bar during hiresfix.)
========================================
Apply LyCORIS model: lora-weights
Text encoder weight: 0.2
Unet weight: 1.5
DyLoRA Dim: None
========================================
```
Second prompt & Hires. fix
<lyco:lora-weights:1.2:2.5>→
```
========================================
Apply LyCORIS model: lora-weights
Text encoder weight: 1.2
Unet weight: 2.5
DyLoRA Dim: None
========================================
(Here is the progress bar during hiresfix.)
========================================
Apply LyCORIS model: lora-weights
Text encoder weight: 0.2
Unet weight: 1.5
DyLoRA Dim: None
========================================
```
If <lyco:> is deleted, it will be restored during Hires.fix.
Is it because of cache settings etc?

**Comment by leoftm** [comment]
Wow, it looks like the equals I pasted from the terminal did a bad job, sorry.

**Comment by KohakuBlueleaf** [comment]
I think the problem is by sd-webui
since this part is not managed by my extension

**Comment by leoftm** [comment]
Sorry, I didn't notice the spec change!
There is a separate prompt input area that is applied during the hires.fix and it was written there!
Sorry for the hassle, thanks for the response!
