### ISSUE TITLE
Does not work with inpainting models

### ISSUE THREAD

**Issue by jaretburkett** [KohakuBlueleaf/a1111-sd-webui-lycoris#39]
```
stable-diffusion-webui/extensions/a1111-sd-webui-lycoris/lycoris.py", line 698, in lyco_apply_weights
  self.weight += lyco_calc_updown(lyco, module, self.weight) * multiplier
  RuntimeError: The size of tensor a (9) must match the size of tensor b (4) at non-singleton dimension 1
```
I was about to look into it myself, I am sure it is just detecting and handling for the extra dimensions of an inpainting model, but before I did, I wanted to make sure it is not a limitation of the LyCORIS algorithm itself.

**Comment by KohakuBlueleaf** [comment]
Inpaint model has their own model arch.
And basically all the lycoris train on all layer which means you basically cannot apply lycoris model to inpaint model
It is normal

If you want to use it, you can try to remove the weight of proj in layer

**Comment by KohakuBlueleaf** [comment]
And, algorithm itself has no limitations on it
