### ISSUE TITLE
How is this different from your Locon extension?

### ISSUE THREAD

**Issue by B00Berry** [KohakuBlueleaf/a1111-sd-webui-lycoris#4]
I already had the Locon extension installed, and had no issue using Lycoris files from the regular Models/Lora folder.  I'm just confused as to how this differs from this one - https://github.com/KohakuBlueleaf/a1111-sd-webui-locon

**Comment by KohakuBlueleaf** [comment]
just use more better way to impl it
to avoid lot of conflict fro mother lora extensions

**Comment by B00Berry** [comment]
OK, so the Locon extension is deprecated & you recommend this Lycoris extension as a replacement?

**Comment by KohakuBlueleaf** [comment]
@B00Berry Yes

**Comment by B00Berry** [comment]
> @B00Berry Yes

So do LoHa models still go in the Lora folder, or into the new LyCoris folder?  A general overview of correct usage and setups would be really helpful here.  Thanks for all your work!

**Comment by KohakuBlueleaf** [comment]
@B00Berry 
1, If you want to use old locon ext, put LyCORIS model in lora folder
2, If you want to use new lycoris ext, put LyCORIS model in LyCORIS folder

Only lycoris ext can support all type of LyCORIS model, (for example: locon ext doesn't support dylora)

**Comment by KohakuBlueleaf** [comment]
@catboxanon If you want to disagree this decision
please make sd-webui be better for extension to make new functionality in the built-in things.
Do you know how annoying that every one send issue to locon extension and almost all of that is casued by other extension?
If I can just avoid these things by just make a stand alone system
Why I need to maintain the old one and worry about sd-webui's update and worry about other extensions

And, BTW, your script forget ckpt and pt file.
