### ISSUE TITLE
[bug]Unable to correctly recognize the additional description of LoRA block weight extension after weight

### ISSUE THREAD

**Issue by anne43983959** [KohakuBlueleaf/a1111-sd-webui-lycoris#43]
The LoRA block weight extension can normally recognize additional network calls in the form of "<lyco: name: weight: block_weight>", but the LyCORIS extension cannot correctly recognize blocks_ weight parameter, error “ ValueError: could not convert string to float: 'ALL' ” was reported.
Although the additional network can function normally, we still hope that the LyCORIS extension can avoid such false positives.

![CY94@9@ UJSNAZL6I8P6AJE](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/115604775/2a3c3e28-6c17-447e-a686-6b03d51794e6)
![GXINFL9HAKYMD IKV18~H}H](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/115604775/7634b60e-84d2-4336-b530-5b2e64e9cabd)
![KRQYJ3S3P_4DB89H~_2$9J5](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/115604775/670a80b5-a61e-456a-8fc7-d963651a9aa4)
![ASB2}6KQQ)K88K2K~58R%0Q](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/115604775/d822d152-ddf0-4bc5-8c34-3e4bef8d3d10)

**Comment by KohakuBlueleaf** [comment]
@anne43983959 你沒看readme
人家說了要用lbw=xxx
不能直接xxx來用
