### ISSUE TITLE
Can't open previews in Extra Networks version dcb9536d

### ISSUE THREAD

**Issue by Gaspatcher** [KohakuBlueleaf/a1111-sd-webui-lycoris#45]
Since update dcb9536d, I'm no longer able to open previews in my Extra Networks.
In the console I have:
AttributeError: 'ExtraNetworksPageLyCORIS' object has no attribute 'get_sort_keys'

When I disable this extension, everything is working fine again.

How can I revert to the version just before?
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/135508099/79ebb7e3-2aea-402b-9ba0-d1ae7c46388b)

**Comment by atmogenic** [comment]
getting the same issue

**Comment by ga780586** [comment]
same here. How do I get the old version back?

**Comment by dtxn** [comment]
Me too. Can't even get Lora.

**Comment by Little-God1983** [comment]
This! Had do disable the extension. Maybe this helps.

Traceback (most recent call last):
  File "D:\AI\SD-2023\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI\SD-2023\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\AI\SD-2023\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI\SD-2023\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI\SD-2023\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\AI\SD-2023\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\AI\SD-2023\modules\ui_extra_networks.py", line 313, in fill_tabs
    refresh()
  File "D:\AI\SD-2023\modules\ui_extra_networks.py", line 330, in refresh
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\AI\SD-2023\modules\ui_extra_networks.py", line 330, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\AI\SD-2023\modules\ui_extra_networks.py", line 121, in create_html
    for item in self.list_items():
  File "D:\AI\SD-2023\extensions\a1111-sd-webui-lycoris\ui_extra_networks_lyco.py", line 33, in list_items
    "sort_keys": {'default': index, **self.get_sort_keys(lyco_on_disk.filename)},
AttributeError: 'ExtraNetworksPageLyCORIS' object has no attribute 'get_sort_keys'

**Comment by Myoko** [comment]
same issues

**Comment by ToniVacaESAT** [comment]
I am in the same situation. I have downgraded to version c1e676b4 (git checkout c1e676b4d75c1ff2bd49f0742036eb8691d10ccd) and, although it works again, it gives an error in git that prevents its automatic update; You have to delete it and reinstall it.

`Failed reading extension data from Git repository (a1111-sd-webui-lycoris): HEAD is a detached symbolic reference as it points to 'c1e676b4d75c1ff2bd49f0742036eb8691d10ccd'`

**Comment by dtxn** [comment]
> I am in the same situation. I have downgraded to version [c1e676b](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/c1e676b4d75c1ff2bd49f0742036eb8691d10ccd) (git checkout [c1e676b](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/c1e676b4d75c1ff2bd49f0742036eb8691d10ccd)) and, although it works again, it gives an error in git that prevents its automatic update; You have to delete it and reinstall it.
> 
> `Failed reading extension data from Git repository (a1111-sd-webui-lycoris): HEAD is a detached symbolic reference as it points to 'c1e676b4d75c1ff2bd49f0742036eb8691d10ccd'`

I'm newbie in this situation. Maybe you could write down short instruction, how to downgrade ? After I updated Lycoris, somehow my additional networks broke and I can't load Loras even if I disabled Lycoris.

**Comment by ToniVacaESAT** [comment]
> > I am in the same situation. I have downgraded to version [c1e676b](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/c1e676b4d75c1ff2bd49f0742036eb8691d10ccd) (git checkout [c1e676b](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/c1e676b4d75c1ff2bd49f0742036eb8691d10ccd)) and, although it works again, it gives an error in git that prevents its automatic update; You have to delete it and reinstall it.
> > `Failed reading extension data from Git repository (a1111-sd-webui-lycoris): HEAD is a detached symbolic reference as it points to 'c1e676b4d75c1ff2bd49f0742036eb8691d10ccd'`
> 
> I'm newbie in this situation. Maybe you could write down short instruction, how to downgrade ? After I updated Lycoris, somehow my additional networks broke and I can't load Loras even if I disabled Lycoris.

First, excuse my atrocious English, I'm Spanish.
Go to the 'a1111-sd-webui-lycoris' directory, click on the folder thumbnail (make the path appear) and type: 'cmd'. Then type: 'git checkout c1e676b4d75c1ff2bd49f0742036eb8691d10ccd' and hit enter

**Comment by KohakuBlueleaf** [comment]
@catboxanon 
I haven't dig into the change you made
Can you help me to solve this problem?

**Comment by KatsuyaIwamoto** [comment]
With the following procedure, both Lora and LyCORIS now work normally.
(1) Disable extension "a1111-sd-webui-lycoris"
(2) Exit the web UI
(3) Launch Web UI, disable automatic update of extension at this time
(4) After starting Web UI, enable "a1111-sd-webui-lycoris" and restart.

**Comment by dtxn** [comment]
> > > I am in the same situation. I have downgraded to version [c1e676b](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/c1e676b4d75c1ff2bd49f0742036eb8691d10ccd) (git checkout [c1e676b](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/c1e676b4d75c1ff2bd49f0742036eb8691d10ccd)) and, although it works again, it gives an error in git that prevents its automatic update; You have to delete it and reinstall it.
> > > `Failed reading extension data from Git repository (a1111-sd-webui-lycoris): HEAD is a detached symbolic reference as it points to 'c1e676b4d75c1ff2bd49f0742036eb8691d10ccd'`
> > 
> > 
> > I'm newbie in this situation. Maybe you could write down short instruction, how to downgrade ? After I updated Lycoris, somehow my additional networks broke and I can't load Loras even if I disabled Lycoris.
> 
> First, excuse my atrocious English, I'm Spanish. Go to the 'a1111-sd-webui-lycoris' directory, click on the folder thumbnail (make the path appear) and type: 'cmd'. Then type: 'git checkout [c1e676b](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/c1e676b4d75c1ff2bd49f0742036eb8691d10ccd)' and hit enter

I think I did what you said, but the problem didn't disappear.
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/132169795/42872145-938c-4063-be3a-ad70744c808f)

And when I try to generate image my Lora doesn't activate:
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/132169795/7061ef99-9956-4c41-b271-d6da9f404c2a)

**Comment by KohakuBlueleaf** [comment]
> > > > I am in the same situation. I have downgraded to version [c1e676b](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/c1e676b4d75c1ff2bd49f0742036eb8691d10ccd) (git checkout [c1e676b](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/c1e676b4d75c1ff2bd49f0742036eb8691d10ccd)) and, although it works again, it gives an error in git that prevents its automatic update; You have to delete it and reinstall it.
> > > > `Failed reading extension data from Git repository (a1111-sd-webui-lycoris): HEAD is a detached symbolic reference as it points to 'c1e676b4d75c1ff2bd49f0742036eb8691d10ccd'`
> > > 
> > > 
> > > I'm newbie in this situation. Maybe you could write down short instruction, how to downgrade ? After I updated Lycoris, somehow my additional networks broke and I can't load Loras even if I disabled Lycoris.
> > 
> > 
> > First, excuse my atrocious English, I'm Spanish. Go to the 'a1111-sd-webui-lycoris' directory, click on the folder thumbnail (make the path appear) and type: 'cmd'. Then type: 'git checkout [c1e676b](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/c1e676b4d75c1ff2bd49f0742036eb8691d10ccd)' and hit enter
> 
> I think I did what you said, but the problem didn't disappear. ![image](https://user-images.githubusercontent.com/132169795/243174162-42872145-938c-4063-be3a-ad70744c808f.png)
> 
> And when I try to generate image my Lora doesn't activate: ![image](https://user-images.githubusercontent.com/132169795/243174232-7061ef99-9956-4c41-b271-d6da9f404c2a.png)

Bro, what you are using is locon extension
not this lycoris extension

and locon ext is basically deprecated

**Comment by KohakuBlueleaf** [comment]
> Oh, I wasn't expecting the PR to get merged that soon. You're probably going to want to revert it until the web UI gets that merged into master, or check if the `get_sort_keys` function exists.

Ok I think I will need to maintain some kind of dev branch

**Comment by dtxn** [comment]
> > > > > I am in the same situation. I have downgraded to version [c1e676b](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/c1e676b4d75c1ff2bd49f0742036eb8691d10ccd) (git checkout [c1e676b](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/c1e676b4d75c1ff2bd49f0742036eb8691d10ccd)) and, although it works again, it gives an error in git that prevents its automatic update; You have to delete it and reinstall it.
> > > > > `Failed reading extension data from Git repository (a1111-sd-webui-lycoris): HEAD is a detached symbolic reference as it points to 'c1e676b4d75c1ff2bd49f0742036eb8691d10ccd'`
> > > > 
> > > > 
> > > > I'm newbie in this situation. Maybe you could write down short instruction, how to downgrade ? After I updated Lycoris, somehow my additional networks broke and I can't load Loras even if I disabled Lycoris.
> > > 
> > > 
> > > First, excuse my atrocious English, I'm Spanish. Go to the 'a1111-sd-webui-lycoris' directory, click on the folder thumbnail (make the path appear) and type: 'cmd'. Then type: 'git checkout [c1e676b](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/c1e676b4d75c1ff2bd49f0742036eb8691d10ccd)' and hit enter
> > 
> > 
> > I think I did what you said, but the problem didn't disappear. ![image](https://user-images.githubusercontent.com/132169795/243174162-42872145-938c-4063-be3a-ad70744c808f.png)
> > And when I try to generate image my Lora doesn't activate: ![image](https://user-images.githubusercontent.com/132169795/243174232-7061ef99-9956-4c41-b271-d6da9f404c2a.png)
> 
> Bro, what you are using is locon extension not this lycoris extension
> 
> and locon ext is basically deprecated

I deleted locon and seems that it helped. Thanks. Still get some error line from Lycoris even if it's deactivated from extensions tab:
Failed reading extension data from Git repository (a1111-sd-webui-lycoris): HEAD is a detached symbolic reference as it points to 'c1e676b4d75c1ff2bd49f0742036eb8691d10ccd'
