### ISSUE TITLE
Models in hidden (dot) directories not shown in extra networks LyCORIS tab

### ISSUE THREAD

**Issue by boredofnames** [KohakuBlueleaf/a1111-sd-webui-lycoris#50]
This falls out of line with the built-in model tabs support there. 
It prevents the setting `System > Load models/files in hidden directories` from being useful for LyCORIS models.

**Comment by Kuresuto12** [comment]
Noticed the same, didn't know if I should put an issue in the extra networks git or in here, but since lycoris isn't supported by the main sd, here seems the best

**Comment by KohakuBlueleaf** [comment]
I will support this these days
