### ISSUE TITLE
Failed to load lycoris

### ISSUE THREAD

**Issue by Lawrenceeeeeeee** [KohakuBlueleaf/a1111-sd-webui-lycoris#51]
It seems that the extension crashes when the webui starts. How to fix this?
```
Error running preload() for D:\Users\Administrator\Desktop\My_Projects\sd-webui-aki\sd-webui-aki-v4\sd-webui-aki-v4\extensions\a1111-sd-webui-lycoris-main\preload.py
Traceback (most recent call last):
  File "D:\Users\Administrator\Desktop\My_Projects\sd-webui-aki\sd-webui-aki-v4\sd-webui-aki-v4\modules\script_loading.py", line 27, in preload_extensions
    module.preload(parser)
  File "D:\Users\Administrator\Desktop\My_Projects\sd-webui-aki\sd-webui-aki-v4\sd-webui-aki-v4\extensions\a1111-sd-webui-lycoris-main\preload.py", line 6, in preload
    parser.add_argument("--lyco-dir", type=str, help="Path to directory with LyCORIS networks.", default=os.path.join(paths.models_path, 'LyCORIS'))
  File "argparse.py", line 1448, in add_argument
  File "argparse.py", line 1814, in _add_action
  File "argparse.py", line 1650, in _add_action
  File "argparse.py", line 1462, in _add_action
  File "argparse.py", line 1599, in _check_conflict
  File "argparse.py", line 1608, in _handle_conflict_error
argparse.ArgumentError: argument --lyco-dir: conflicting option string: --lyco-dir

```

**Comment by LieDeath** [comment]
you have not pointed to a exist directory. please add a path which contain the LyCORIS models.
for example:
```
--lycoris-dir .\stable-diffusion-webui\models\lycoris\
```

**Comment by Lawrenceeeeeeee** [comment]
> > It seems that the extension crashes when the webui starts. How to fix this?
> > ```
> > Error running preload() for D:\Users\Administrator\Desktop\My_Projects\sd-webui-aki\sd-webui-aki-v4\sd-webui-aki-v4\extensions\a1111-sd-webui-lycoris-main\preload.py
> > Traceback (most recent call last):
> >   File "D:\Users\Administrator\Desktop\My_Projects\sd-webui-aki\sd-webui-aki-v4\sd-webui-aki-v4\modules\script_loading.py", line 27, in preload_extensions
> >     module.preload(parser)
> >   File "D:\Users\Administrator\Desktop\My_Projects\sd-webui-aki\sd-webui-aki-v4\sd-webui-aki-v4\extensions\a1111-sd-webui-lycoris-main\preload.py", line 6, in preload
> >     parser.add_argument("--lyco-dir", type=str, help="Path to directory with LyCORIS networks.", default=os.path.join(paths.models_path, 'LyCORIS'))
> >   File "argparse.py", line 1448, in add_argument
> >   File "argparse.py", line 1814, in _add_action
> >   File "argparse.py", line 1650, in _add_action
> >   File "argparse.py", line 1462, in _add_action
> >   File "argparse.py", line 1599, in _check_conflict
> >   File "argparse.py", line 1608, in _handle_conflict_error
> > argparse.ArgumentError: argument --lyco-dir: conflicting option string: --lyco-dir
> > ```
> 
> You have two lycoris extension in your environment

Problem solved! Thanks!

**Comment by LieDeath** [comment]
> > you have not pointed to a exist directory. please add a path which contain the LyCORIS models. for example:
> > ```
> > --lycoris-dir .\stable-diffusion-webui\models\lycoris\
> > ```
> 
> Don't mistake the problem here The error is triggered then the extension attempts to add arguments for parser Which is earlier then parsing the user input

oh... sorry, i am still learning, and can't view the full sight of issue. my advice only
