### ISSUE TITLE
API Support

### ISSUE THREAD

**Issue by vleeuwenmenno** [KohakuBlueleaf/a1111-sd-webui-lycoris#53]
I am writing an app to use A1111 on phone, and I'd like to have an API call to fetch lycoris just like the one for lora.
Is there any possibility for this to be added? Also, some shameless promotion, let me know if you'd like to try the app, it's in TestFlight at the moment 😅

**Comment by vleeuwenmenno** [comment]
FYI I created a PR that adds this #54 once merged it works just like the lora endpoints 👍🏻

**Comment by KohakuBlueleaf** [comment]
@vleeuwenmenno Merged!
sry for late response
