### ISSUE TITLE
When i put LyCORIS to its folder on "models" folder, the webUI is not booting up

### ISSUE THREAD

**Issue by TheRevivalOfWisdom** [KohakuBlueleaf/a1111-sd-webui-lycoris#55]
Hi, I installed LyCORIS from "Install from URL" SECTİON İN Extentions tab on the UI. But when i put any kind of LyCORIS on it's folder that's in models/LyCORIS i can't boot up the webUI, it says that it can't read the LyCORIS' that's why it won't give me the URL that's normally been used to enter the webUI.

**Comment by TheRevivalOfWisdom** [comment]
Idk is it because of my gig but here's my gig:

3080ti SUPRIM X
Ryzen 7 5800x3D
Corsair Vengeance RT 3600Mhz CL16 32GB Ram

**Comment by KohakuBlueleaf** [comment]
What's your sd-webui version?

**Comment by TheRevivalOfWisdom** [comment]
> What's your sd-webui version?

Sorryi kinda novice at this, how can i know the version of the webUI i'm using?

**Comment by KohakuBlueleaf** [comment]
@TheRevivalOfWisdom 
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/59680068/4cbdcd71-97f3-41be-88c6-526a0070a4e5)
When you startup the webui
you should get something like these

**Comment by TheRevivalOfWisdom** [comment]
![Screenshot 2023-07-17 184313](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/98627077/ac3fd4ff-1dc8-4ff1-9a3f-a38c6291aee3)
I only got this when i opening webUI

**Comment by KohakuBlueleaf** [comment]
@TheRevivalOfWisdom your sd webui is way too old
Please consider update it

**Comment by TheRevivalOfWisdom** [comment]
> @TheRevivalOfWisdom your sd webui is way too old Please consider update it

It's fixed when I updated the webUI. Thanks for suggesting me that.
