### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by RongWroom** [KohakuBlueleaf/a1111-sd-webui-lycoris#56]
Hey, I've never used a Lyco before but I'm getting this error:

RuntimeError: The size of tensor a (768) must match the size of tensor b (1024) at non-singleton dimension 1

Can you help me understand what I'm doing wrong? I followed the install instructions and have installed Lora's on Stable Diffusion before.

Thank you

**Comment by KohakuBlueleaf** [comment]
@RongWroom you are trying to load sd1 lyco for sd2 model or vice versa
