### ISSUE TITLE
Conflicts with latest A1111 extra networks implementation

### ISSUE THREAD

**Issue by jaretburkett** [KohakuBlueleaf/a1111-sd-webui-lycoris#59]
On latest automatic11111 master, with their rework of the extra networks. I noticed if you run a generation with a lycoris, and then add a lora, the lycoris does not function anymore. If you remove lyco generate again, then add it back, the lora does not function anymore. You can only get them both on there if you run an empty prompt, and then add all the networks together

**Comment by jaretburkett** [comment]
It looks like they added native support https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/2164578738edba6f56c4e95409c56f9ccef442e0 and that is the reason for the conflicts.

**Comment by KohakuBlueleaf** [comment]
Actually the rework is a collaboration for merging lycoris into built-in lora XD

**Comment by younyokel** [comment]
> Actually the rework is a collaboration for merging lycoris into built-in lora XD

is the extension now redundant?

**Comment by KohakuBlueleaf** [comment]
> > Actually the rework is a collaboration for merging lycoris into built-in lora XD
> 
> is the extension now redundant?

Yes
