### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by fireaid** [KohakuBlueleaf/a1111-sd-webui-lycoris#6]
Creating model from config: C:\Users\Mrfir\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: C:\Users\Mrfir\stable-diffusion-webui\models\Stable-diffusion\anything-v4.5.vae.pt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(7): bad_prompt_version2, chihunhentai2, cutesexyrobutts, jojo-stand, lancer_alter-9000, mana, raita
Model loaded in 3.4s (load weights from disk: 0.9s, create model: 0.2s, apply weights to model: 0.3s, apply half(): 0.5s, load VAE: 0.3s, move model to device: 0.5s, load textual inversion embeddings: 0.7s).
Traceback (most recent call last):
  File "C:\Users\Mrfir\stable-diffusion-webui\launch.py", line 361, in <module>
    start()
  File "C:\Users\Mrfir\stable-diffusion-webui\launch.py", line 356, in start
    webui.webui()
  File "C:\Users\Mrfir\stable-diffusion-webui\webui.py", line 205, in webui
    shared.demo = modules.ui.create_ui()
  File "C:\Users\Mrfir\stable-diffusion-webui\modules\ui.py", line 468, in create_ui
    extra_networks_ui = ui_extra_networks.create_ui(extra_networks, extra_networks_button, 'txt2img')
  File "C:\Users\Mrfir\stable-diffusion-webui\modules\ui_extra_networks.py", line 175, in create_ui
    page_elem = gr.HTML(page.create_html(ui.tabname))
  File "C:\Users\Mrfir\stable-diffusion-webui\modules\ui_extra_networks.py", line 90, in create_html
    for item in self.list_items():
  File "C:\Users\Mrfir\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris-main\ui_extra_networks_lyco.py", line 21, in list_items
    "preview": self.find_preview(path),
AttributeError: 'ExtraNetworksPageLyCORIS' object has no attribute 'find_preview'. Did you mean: 'link_preview'?

**Comment by KohakuBlueleaf** [comment]
Your sd-webui's version is too old
I will try to do a compatible version for both new/old sd-webui

What is the commit of your sd-webui?

**Comment by magicFeirl** [comment]
> Your sd-webui's version is too old I will try to do a compatible version for both new/old sd-webui
> 
> What is the commit of your sd-webui?

Same proble here. My webui commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8

**Comment by KohakuBlueleaf** [comment]
> > Your sd-webui's version is too old I will try to do a compatible version for both new/old sd-webui
> > What is the commit of your sd-webui?
> 
> Same proble here. My webui commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8

Your commit is too old I guess.

**Comment by zhanggouxiang** [comment]
I have same problem :(

**Comment by WissF** [comment]
Same problem. Plus, if you close the webui console, you won’t start it until you delete the downloaded file to the LyCORIS folder. It makes no sense to update the assembly now, a lot of things are broken and it is best to use stable versions before March 5th.

**Comment by KohakuBlueleaf** [comment]
@WissF There are not things are broken.
Just extensions doesn't update for new version webui
It makes no sense to not update to latest commit.
