### ISSUE TITLE
A1111 not Detecting LyCORIS in Colab

### ISSUE THREAD

**Issue by vararth** [KohakuBlueleaf/a1111-sd-webui-lycoris#60]
I am using Colab anbd have added this extension as well as the Civitai Helper (with the LyCORIS parsing fork)

In SD 1.5 - all LyCORIS get detected but for some reason, when I am using SDXL - no LyCORIS gets detected even though they are in the correct folder - can you suggest a fix or workaround?

**Comment by KohakuBlueleaf** [comment]
Sd webui 1.5 will detect lora/lycoris version
Only the lora for your arch will be showed

So sd1.x lora will not show when you using sdxl

It doesn't have compatibility across architecture

**Comment by vararth** [comment]
Yeah, I have different setups for SD1.5 and SDXL

When I moved the LyCORIS files to the lora folder for SDXL, it started working properly
