### ISSUE TITLE
The LyCORIS button is not displayed

### ISSUE THREAD

**Issue by Tupload** [KohakuBlueleaf/a1111-sd-webui-lycoris#65]
I use SD 1.6.0 no button is displayed on web ui

**Comment by KohakuBlueleaf** [comment]
Your model should be displayed in lora tab
you can check the readme or other issue

**Comment by Tupload** [comment]
I tried to use a LyCORIS model I moved the file to the Lora folder I integrate it as soon as possible it writes <lora:avaryana:1> instead of lyco

**Comment by KohakuBlueleaf** [comment]
yes
it should be <lora:>

**Comment by Tupload** [comment]
okay thx ^^
