### ISSUE TITLE
Disconnection error when using Lora and Locon together

### ISSUE THREAD

**Issue by DOODED** [KohakuBlueleaf/a1111-sd-webui-lycoris#7]
![error1](https://user-images.githubusercontent.com/126422099/231415673-7007ff32-3435-4dd7-b2d6-bbd517b35961.JPG)
![error2](https://user-images.githubusercontent.com/126422099/231415680-1fd79786-df55-4394-9c4a-3f152bcc9c7e.JPG)

I get this error when I change lora's weight. What should I do?
I'm using colab, and every time I change lora's weight, it disconnects.

**Comment by KohakuBlueleaf** [comment]
I don't know
There is no error message so it's impossible to debug this

**Comment by KohakuBlueleaf** [comment]
And if you don't have locon ext (the deprecated one)
And you only get error when change lora

This is very possible a bug in sd-webui's built-in lora
So if there is no further information

I cannot help you
