### ISSUE TITLE
Can't find "LyCORIS" tab in the extra networks page

### ISSUE THREAD

**Issue by Kotori05** [KohakuBlueleaf/a1111-sd-webui-lycoris#9]
I install it and restart the webui process
no error
it create LyCORIS folder in ./WebUI/models/ , but I can't find "LyCORIS" tab in the extra networks page

another question
Is it that LoCon extension function all transfered to LyCORIS extension?
Is it necessary to deactivate LoCon extension?

**Comment by KohakuBlueleaf** [comment]
1, check your sd-webui's version (commit)
2, yes, and lycoris ext already has more functionality
3, no, but if yoy met some problems of built in lora, I recommend you to deactivate it.

**Comment by Kotori05** [comment]
cloned another webui lastest, and only installed LyCORIS extension, still can't find "LyCORIS" tab in the extra networks page.

**Comment by Kotori05** [comment]
no error, LyCORIS extension did not output any information.

    (sd) root@Asrock:/mnt/d/WSL# git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git
    Cloning into 'stable-diffusion-webui'...
    remote: Enumerating objects: 17850, done.
    remote: Total 17850 (delta 0), reused 0 (delta 0), pack-reused 17850
    Receiving objects: 100% (17850/17850), 28.25 MiB | 5.00 MiB/s, done.
    Resolving deltas: 100% (12507/12507), done.
    (sd) root@Asrock:/mnt/d/WSL# cd ./stable-diffusion-webui
    (sd) root@Asrock:/mnt/d/WSL/stable-diffusion-webui# python ./launch.py --xformers --api
    Python 3.10.6 (main, Oct 24 2022, 16:07:47) [GCC 11.2.0]
    Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
    Cloning Stable Diffusion into /mnt/d/WSL/stable-diffusion-webui/repositories/stable-diffusion-stability-ai...
    Cloning Taming Transformers into /mnt/d/WSL/stable-diffusion-webui/repositories/taming-transformers...
    Cloning K-diffusion into /mnt/d/WSL/stable-diffusion-webui/repositories/k-diffusion...
    Cloning CodeFormer into /mnt/d/WSL/stable-diffusion-webui/repositories/CodeFormer...
    Cloning BLIP into /mnt/d/WSL/stable-diffusion-webui/repositories/BLIP...
    Installing requirements for Web UI
    Launching Web UI with arguments: --xformers --api
    100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.97G/3.97G [10:41<00:00, 6.65MB/s]
    Calculating sha256 for /mnt/d/WSL/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors: 6ce0161689b3853acaa03779ec93eafe75a02f4ced659bee03f50797806fa2fa
    Loading weights [6ce0161689] from /mnt/d/WSL/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors
    Creating model from config: /mnt/d/WSL/stable-diffusion-webui/configs/v1-inference.yaml
    LatentDiffusion: Running in eps-prediction mode
    DiffusionWrapper has 859.52 M params.
    Applying xformers cross attention optimization.
    Textual inversion embeddings loaded(0):
    Model loaded in 40.0s (calculate hash: 10.7s, load weights from disk: 1.0s, create model: 0.3s, apply weights to model: 25.4s, apply half(): 0.3s, load VAE: 1.5s, move model to device: 0.8s).
    Running on local URL:  http://127.0.0.1:7860
    
    To create a public link, set `share=True` in `launch()`.
    Startup time: 702.7s (import torch: 2.0s, import gradio: 0.6s, import ldm: 0.5s, other imports: 1.7s, list SD models: 655.1s, setup codeformer: 0.4s, load scripts: 1.1s, load SD checkpoint: 40.2s, create ui: 0.3s, gradio launch: 0.6s, scripts app_started_callback: 0.1s).

**Comment by KohakuBlueleaf** [comment]
If this is the full procedure.
It looks like you haven't reboot after install the extension...?
or you only use "apply and restart"?

**Comment by Kotori05** [comment]
yes, i obay the md totally reboot the webui

**Comment by bow3nwang** [comment]
same problem

**Comment by msinc1228** [comment]
AttributeError: 'Namespace' object has no attribute 'lyco_dir'

**Comment by KohakuBlueleaf** [comment]
> AttributeError: 'Namespace' object has no attribute 'lyco_dir'

You forgot to reboot the sd-webui

**Comment by AmitShashi** [comment]
@KohakuBlueleaf
i found solution to this problem, install kitchen theme or other theme it will refresh ui cache. and you can find those lycoris tab directly in txt2img and img2img tabs on right side. no need to go to extra tab. why dont you update this extension. you can easily do it right. and one more thing i love Taiwanese bravest and kindest people on earth.

**Comment by slashedstar** [comment]
Oh, adding an option to set the folder (or automatically use the one set by --lora-dir in the args) would be nice, I was a bit confused as to why it wasn't finding the models, it uses the default path

**Comment by Kotori05** [comment]
@AmitShashi thank you! it works
